knp_snappy:
    process_timeout: 13600
    pdf:
        enabled:    true
        binary:     '%env(WKHTMLTOPDF_PATH)%'
        options:
            margin-bottom: 0
            margin-top: 0
            margin-left: 0
            margin-right: 0
            orientation: Portrait
            page-size: A4
            disable-smart-shrinking: true
            dpi: 98
            zoom: 1
    image:
        enabled:    true
        binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
